services:
  agent_semgrep:
    build:
      context: ../
      dockerfile: infra/agent.semgrep.Dockerfile
    environment:
      - ORCH_URL=http://orchestrator:8080
      - TENANT_ID=t_demo
      - AGENT_NAME=semgrep1
      - AGENT_TOKEN=${AGENT_TOKEN:-}
    depends_on:
      - orchestrator
