# Development overrides
# Automatically loaded when using docker compose

version: '3.8'

services:
  orchestrator:
    build:
      target: development
    volumes:
      - ../orchestrator:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: ["flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"]

  ui:
    build:
      target: development
    volumes:
      - ../ui:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
