services:
  agent_nuclei_v2:
    build:
      context: ../
      dockerfile: infra/agent.nuclei.v2.Dockerfile
    environment:
      - ORCH_URL=http://orchestrator:8080
      - TENANT_ID=t_demo
      - AGENT_NAME=nucleiv2
      - AGENT_TOKEN=${AGENT_TOKEN:-}
    depends_on:
      - orchestrator
