services:
  db:
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-aitest}"]
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 3s
