services:
  agent_web_discovery:
    build:
      context: ../
      dockerfile: infra/agent.web_discovery.Dockerfile
    environment:
      - ORCH_URL=http://orchestrator:8080
      - TENANT_ID=t_demo
      - AGENT_NAME=discover1
      - AGENT_TOKEN=${AGENT_TOKEN:-}
    depends_on:
      - orchestrator
