services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    container_name: oauth2-proxy
    env_file:
      - ./infra/auth/.env.auth
    command: ["--config=/config/oauth2_proxy.cfg"]
    volumes:
      - ./infra/auth/oauth2_proxy.cfg:/config/oauth2_proxy.cfg:ro
    depends_on:
      - orchestrator

  reverse-proxy:
    image: nginx:1.25-alpine
    container_name: reverse-proxy
    ports:
      - "8081:8081"
    volumes:
      - ./infra/auth/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - oauth2-proxy
      - orchestrator
