services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aitest
  orchestrator:
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/aitest
      - DB_URL=postgresql+psycopg://postgres:postgres@db:5432/aitest
      - DB_DSN=postgresql+psycopg://postgres:postgres@db:5432/aitest
