services:
  agent_kali_remote:
    build:
      context: ../
      dockerfile: infra/agent.kali.remote.Dockerfile
    environment:
      - ORCH_URL=http://orchestrator:8080
      - TENANT_ID=t_demo
      - AGENT_NAME=kali_remote
      - AGENT_TOKEN=${AGENT_TOKEN:-}
      - SSH_HOST=${SSH_HOST:-}
      - SSH_USER=${SSH_USER:-kali}
      - SSH_PORT=${SSH_PORT:-22}
      - SSH_KEY_BASE64=${SSH_KEY_BASE64:-}
      - SSH_PASSWORD=${SSH_PASSWORD:-}
      - ALLOW_ACTIVE_SCAN=${ALLOW_ACTIVE_SCAN:-0}
    depends_on:
      - orchestrator
