services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    env_file:
      - ./infra/auth/.env.auth
    volumes:
      - ./infra/auth/oauth2_proxy.cfg:/etc/oauth2_proxy.cfg:ro
    command: ["--config=/etc/oauth2_proxy.cfg"]
    depends_on:
      - orchestrator
    ports:
      - "4180:4180"

  reverse-proxy:
    image: nginx:1.25-alpine
    volumes:
      - ./infra/auth/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - TENANT_DEFAULT=${TENANT_DEFAULT:-t_demo}
    depends_on:
      - oauth2-proxy
    ports:
      - "8081:8081"
