services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: ai_testing
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  opa:
    image: openpolicyagent/opa:0.65.0-rootless
    command: ["run","--server","--addr=0.0.0.0:8181","/policies"]
    volumes:
      - ../policies:/policies:ro
    ports:
      - "8181:8181"

  orchestrator:
    build:
      context: ../
      dockerfile: infra/orchestrator.Dockerfile.v2
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg://app:app@db:5432/ai_testing
      - DEV_BYPASS_AUTH=true
      - REQUIRE_MFA=false
      - OIDC_ISSUER=
      - OIDC_AUDIENCE=
      - OPA_URL=http://opa:8181/v1/data/pentest/policy
      - SIMULATE_PROGRESS=true
      - SLACK_WEBHOOK=
      - ARTIFACT_DIR=/app/data/artifacts
    depends_on:
      - db
      - opa
    volumes:
      - ../catalog:/app/catalog
      - ../schemas:/app/schemas
      - ../policies:/app/policies
      - ../orchestrator:/app/orchestrator
      - artifacts_data:/app/data

  kali_agent:
    build:
      context: ../
      dockerfile: infra/agent.Dockerfile
    environment:
      - ORCH_URL=http://orchestrator:8080
      - TENANT_ID=t_demo
    depends_on:
      - orchestrator

volumes:
  db_data:
  artifacts_data:
