name: CI_v3 (build→db+opa→migrate→api→smoke)

on:
  push:
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build orchestrator image
        run: |
          docker compose -f infra/docker-compose.v2.yml build orchestrator

      - name: Bring up DB + OPA (compat) only
        run: |
          docker compose -f infra/docker-compose.v2.yml -f infra/docker-compose.opa.compat.yml -f infra/docker-compose.db.ci.yml -f infra/docker-compose.health.yml up -d db opa
          echo "Waiting for DB health..."
          for i in $(seq 1 60); do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose -f infra/docker-compose.v2.yml ps -q db) 2>/dev/null || echo "starting")
            if [ "$status" = "healthy" ]; then echo "DB is healthy"; break; fi
            sleep 2
          done

      - name: Migrate schema (alembic upgrade head)
        run: |
          docker compose -f infra/docker-compose.v2.yml -f infra/docker-compose.opa.compat.yml -f infra/docker-compose.db.ci.yml run --rm --no-deps orchestrator alembic upgrade head

      - name: Start full stack
        run: |
          docker compose -f infra/docker-compose.v2.yml -f infra/docker-compose.opa.compat.yml -f infra/docker-compose.db.ci.yml -f infra/docker-compose.ci.yml up -d

      - name: Wait for API
        run: |
          bash scripts/wait_for_api_v153.sh http://localhost:8080/health 90

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Smoke test
        env:
          API: http://localhost:8080
          TENANT: t_demo
        run: |
          python scripts/ci_smoke.py

      - name: Show logs on failure
        if: failure()
        run: |
          bash scripts/print_logs_on_fail_v153.sh
